#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/../../../Libraries/vendor/autoload.php';

use Composer\Autoload\ClassLoader;

if (!isset($loader)) {
    $loader = new ClassLoader();
}

// Manually register namespace-to-directory mappings
$loader->addPsr4('App\\', __DIR__ . '/app/');
$loader->addPsr4('Database\\Factories\\', __DIR__ . '/database/factories/');
$loader->addPsr4('Database\\Seeders\\', __DIR__ . '/database/seeders/');
$loader->addPsr4('CustomNamespace\\', __DIR__ . '/CustomNamespace/');

// Register the autoloader
$loader->register();


// Bootstrap Laravel and handle the command...
$app = (require_once __DIR__.'/bootstrap/app.php');
$status = $app->handleCommand(new ArgvInput);

exit($status);
